# Generated by Django 3.0.3 on 2020-05-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=20)),
                ('number_beds', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=5)),
                ('zip', models.IntegerField()),
                ('telefone', models.CharField(max_length=200)),
                ('fax', models.CharField(max_length=200)),
                ('admin', models.CharField(max_length=200)),
                ('admin_email', models.EmailField(max_length=254)),
                ('sw', models.CharField(max_length=200)),
                ('sw_email', models.EmailField(max_length=254)),
                ('markt', models.CharField(max_length=200)),
                ('markt_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
