# Generated by Django 3.0.3 on 2020-05-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20200511_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('number_beds', models.CharField(blank=True, max_length=20, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=5, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=200, null=True)),
                ('fax', models.CharField(blank=True, max_length=200, null=True)),
                ('admin', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sw', models.CharField(blank=True, max_length=200, null=True)),
                ('sw_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('markt', models.CharField(blank=True, max_length=200, null=True)),
                ('markt_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
