# Generated by Django 3.0.3 on 2020-05-12 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_adddata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddData',
        ),
    ]
