# Generated by Django 3.0.3 on 2020-05-12 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_delete_adddata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='address',
        ),
        migrations.RemoveField(
            model_name='table',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='table',
            name='admin_email',
        ),
        migrations.RemoveField(
            model_name='table',
            name='city',
        ),
        migrations.RemoveField(
            model_name='table',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='table',
            name='markt',
        ),
        migrations.RemoveField(
            model_name='table',
            name='markt_email',
        ),
        migrations.RemoveField(
            model_name='table',
            name='number_beds',
        ),
        migrations.RemoveField(
            model_name='table',
            name='region',
        ),
        migrations.RemoveField(
            model_name='table',
            name='state',
        ),
        migrations.RemoveField(
            model_name='table',
            name='sw',
        ),
        migrations.RemoveField(
            model_name='table',
            name='sw_email',
        ),
        migrations.RemoveField(
            model_name='table',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='table',
            name='zip',
        ),
    ]
